# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Rigo's Web
email: rigo.reddig@gmail.com
domain: rigred.github.io
url: https://rigred.github.io
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my digital workshop. 
  This is a journal of hardware archaeology and a brain dump for the cursed knowledge acquired while working with tech. 
  It's a collection of lab notes from the front lines, documenting the process of disassembling things never meant to be opened, 
  designing custom PCBs to bridge hardware timelines, and turning sheer spite into working prototypes.

Fueled by solder fumes and a belief in low-level sorcery, this is where we answer the question, "I wonder if I can make this work again?" If it clicks, whines, or boots from a floppy, you'll probably find it here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  rigred

remote_theme: rigred/jekyll-theme-squishy

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-toc
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

plugins_dir: _plugins

# jekyll-toc configuration
toc:
  min_level: 2
  max_level: 4

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
jekyll-archives:
   enabled:
     - categories
     - tags
   layouts:
     category: archive-taxonomy
     tag: archive-taxonomy
   permalinks:
     category: /categories/:name/
     tag: /tags/:name/

compress_html:
  clippings: all
  ignore:
    envs: development

# Optional: Enable SASS compression
sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include: ["_pages"]

permalink: /:categories/:title/
breadcrumbs: true
paginate: 5 # amount of posts to show
paginate_path: /page:num/

search: true
search_full_content: true

defaults:
# Default front matter settings (optional but recommended)
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      toc: false # Disable TOC by default for all posts
  - scope:
      path: ""
      type: hardware
    values:
      layout: post
      toc: true
  - scope:
      path: ""
      type: software
    values:
      layout: post
  - scope:
      path: ""
      type: projects
    values:
      layout: post
  - scope:
      path: ""
      type: misc
    values:
      layout: post

collections_dir: docs
collections:
  hardware:
    output: true
    permalink: /hardware/:name/
  software:
    output: true
    permalink: /software/:name/
  projects:
    output: true
    permalink: /projects/:name/
  misc:
    output: true
    permalink: /misc/:name/
  scripts:
    output: true
    permalink: /scripts/:name/

